### ISSUE TITLE
Criação e alinhamento de todo o plano de comunicação

### ISSUE THREAD

**Issue by henriquedutra** [fga-eps-mds/2019.1-Lino#6]
- [x] Definição de ferramenta de comunicação rápida
- [x] Definição de ferramenta de comunicação geral
- [x] Organizar salas na ferramenta escolhida
- [x] Verificar devida instalação de aplicativo e notificações por todos os membros
- [x] Preenchimento de todas as planilhas de horários disponíveis, datas ausentes
- [x] Alinhamento de reuniões semanais e diárias
